language: node_js
node_js:
- '8'
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _book
  on:
    branch: master
env:
  global:
    secure: LYiNFpVCqpG60xUkciTb5BnZpSIW+ZXtYD25Y8pGT7H5Vol+i6/SS55eazT7BLzACpv9q1m5k634tL4vDfPowOzvAgqXBSpzRJypkUQL2feFCZ5HunbgHv56It7gbHnEDsmnL5D/oQBzlRgpaWjfOv0hDryMzfhTAO4Hn6FkoHs3xbFFX6n//rNI+HwWvk6JDnjmGYEsquMgxsMOG73BhWdOM8q//VwEaj7M608OSMOLYzvrF9cFaOxdXyjLXW3DB2BBs+Nu2VtzhPz6458He9ZLcxM/SqiA2TMtxPyVFUOPLV8pR3EAq5qUzrJMV8n+cx+UTbff/y+MtItQDBrTI+TLd5eFgtyOuTvu/R6erVz9KhGkWieLeAot/XbDUw67A3+FKwMpn2lzv1zOAWk4yBFyquV+hS6z7e9e+m2l+Hl1jEZ3ekJrlPsx9wNb9ZOQ1uRKuJcnT1OfaZ/1HRyaIsfX1Tnl+/G8vGN9Pg8/aBf27s31trxczN9meDUMdP3V5IN3yU3qnuaSec8tUnwjH1vGi27coRglOtab1CQFg2C8bI8GTuxoI1SvWuv2Vka32FH6VO9mwFt51jYis1acdDS1j3dz+OGwK5HzQa3aYAAXEpMI/qtiDsr75xSLlGPuqhSyIFXWcHz/twVaFj9IQ0H8aYbkGXVnG7eBoFxb6wQ=
